version: "3.7"

services:
  database:
    image: postgres
    container_name: database_talk_to_me
    # restart: always
    ports:
      - 5433:5432
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: talk_to_me
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app

volumes:
  pgdata:
    driver: local
